### ISSUE TITLE
Drop down bug

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#807]
#### Expected behavior
I was expecting all server list in settings to accommodate my phone screen.

#### Actual behavior

The server lists display longer than my phone screen so it's hard to select bottom servers.

<img src="https://i.ibb.co/vsYKsG1/Screenshot-2019-05-09-08-33-00.png" alt="Screenshot-2019-05-09-08-33-00" border="0">

#### How to reproduce

- Open eSteem mobile app
- Open Settings
- Disable Push notification
-  Go to **Server*** and click the drop down after it to switch between servers.

***
* App version: v2.1.0
* Operating system: Android 8.0.1
***

#### Recording Of The Bug

--

**Comment by horpeyloaded** [comment]
Still not fixed

**Comment by mistikk** [comment]
@horpeyloaded it is fixed, can you test again?

**Comment by horpeyloaded** [comment]
Not fixed @mistikk other dropdowns are okay but the server settings reported here not fixed

**Comment by mistikk** [comment]
can you send a ss? @horpeyloaded

**Comment by feruzm** [comment]
@horpeyloaded I think what you need to do is, in Settings page scroll until end of the page and then open drop down for server list. You will see that it is scrollable

**Comment by feruzm** [comment]
Oh I see it is end of page.

**Comment by horpeyloaded** [comment]
@mistikk the screenshot is attached on the first post here.

**Comment by horpeyloaded** [comment]
@feruzm, it works fine only when you have Push notification enabled.
